# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
    identifier: Home
  - name: About
    url: '#about'
    weight: 10
    parent: Home
  - name: Blog
    url: '#posts'
    weight: 20
  - name: Solutions
    url: '#services'
    weight: 30
    identifier: Solutions
  - name: Apps
    url: '/project/apps'
    weight: 31
    parent: Solutions
  - name: Software
    url: '#releases'
    weight: 32
    parent: Solutions
#  - name: Use cases
#    url: '#usecase'
#    weight: 34
#    parent: Solutions
  - name: Code
    url: '/category/r-bloggers/'
    weight: 34
    parent: Solutions
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: Open Science Repository &#128279;
    url: 'https://zenodo.org/communities/music_observatory'
    weight: 41
    parent: Data
  - name: API
    url: '#data'
    weight: 42
    parent: Data
  - name: Projects
    url: '#projects'
    weight: 50
    identifier: Projects
  - name: Overview
    url: '#projects'
    weight: 51
    parent: Projects
#  - name: Publications
#    url: '#featured'
#    weight: 50
#    identifier: Publications
#  - name: Featured
#    url: '#featured'
#    weight: 50
#    parent: Publications
#  - name: All Publications
#    url: '#publications'
#    weight: 52
#    parent: Publications
  - name: Contributors
    url: '#contributors'
    weight: 70
    identifier: Contributors
  - name: Contact
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '#contact'
    weight: 91
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact
  - name: Meetups in Europe
    url: '/meetup'
    weight: 93
    parent: Contact

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
